### ISSUE TITLE
About testing accuracy

### ISSUE THREAD

**Issue by MAGI003769** [aqibsaeed/Place-Recognition-using-Autoencoders-and-NN#1]
Hi,
Thanks for your awesome implementation that makes our work easier.
Having run this code based on UJIIndoorLoc database, however, the original code cannot reach over 90% testing accuracy. I think it blames some settings in this program which is not definitely consistent with the detailed settings mentioned in the [paper](https://arxiv.org/pdf/1611.02049v1.pdf):
 - Jointly scaling the raw material
 - Using -110 to represent the lack of signal rather than 100 which is used in database.

These can help to achieve the expected performance according to paper.

**Comment by aqibsaeed** [comment]
Glad you found it useful. 
Yeah, I wanted to provide high level implementation and not to reproduce the results mentioned in the paper. Interested reader can always look into the paper for specific settings  :) However, thank you very much for pointing this out.
