### ISSUE TITLE
i have a question,how to save or print the predicted result?

### ISSUE THREAD

**Issue by sportzhang** [aqibsaeed/Place-Recognition-using-Autoencoders-and-NN#3]
i have read you paper and code,and get a lot,but i have a question:how to save or print the predicted result of the test data,that is the predicted label.because your code just give the final accuracy,no the predicted result.
thank you!!!!waiting for your response!

**Comment by aqibsaeed** [comment]
predictions = session.run(y_, feed_dict={X: test_features})
numpy.save("predictions", predictions)
print(predictions)

**Comment by sportzhang** [comment]
thank you.I try to use the code you give above,but the result like this:
prediction:
[[ 0.0332829   0.03339982  0.03321473 ...,  0.03326011  0.03329735
   0.03331449]
 [ 0.03328576  0.03339886  0.03321296 ...,  0.03325977  0.03329827
   0.03331491]
 [ 0.03328383  0.03339922  0.03321422 ...,  0.03326022  0.03329772
   0.03331431]
 ..., 
 [ 0.03329009  0.03339841  0.03321114 ...,  0.03325898  0.03329992
   0.03331687]
 [ 0.03328894  0.03339869  0.03321172 ...,  0.03325906  0.03329946
   0.03331647]
 [ 0.03328796  0.03339903  0.03321234 ...,  0.0332591   0.03329911
   0.0333163 ]]
can i get the real label,that is the combine of Building and Floor.?
because what we predict is which Building and which Floor.
so can we get the this label?like the original labels:
>>>labels
array(['12', '12', '12', ..., '13', '13', '13'], dtype=object)

looking forward to your reply,thank you so much!!!
